# Generated by Django 2.2.1 on 2020-09-18 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(1, 'shopping'), (2, 'submitted'), (3, 'canceled'), (4, 'sent')]),
        ),
    ]
